'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {useEconexoData} from '@/lib/econexo-data';
import {defaultSupplierCategories,supplierCategoryId} from '@/lib/supplier-categories';

export function AddUser(){
 const {createProfile,configured}=useEconexoData();
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState<'admin'|'employee'>('employee'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <form onSubmit={async e=>{e.preventDefault();setMessage('');if(name.trim().length<2||!/^\S+@\S+\.\S+$/.test(email)||configured&&password.length<12){setMessage('Completa nombre, correo válido y una contraseña de al menos 12 caracteres.');return;}setBusy(true);try{await createProfile({full_name:name.trim(),email:email.trim().toLowerCase(),role,password});setMessage(configured?'Usuario creado.':'Usuario de demostración agregado.');setName('');setEmail('');setPassword('')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}}}>
 <div className="settings-head"><h2>Agregar usuario</h2><p>{configured?'Crea una cuenta para acceder al sistema.':'Los usuarios de prueba aparecen en Usuarios y en el selector de responsable.'}</p></div>
 <div className="form-grid"><label>Nombre completo<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label>Correo electrónico<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Rol<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="employee">Empleado</option><option value="admin">Administrador</option></select></label>{configured&&<label>Contraseña inicial<input required type="password" minLength={12} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}</div><p role="status">{message}</p><Button disabled={busy} type="submit">{busy?'Guardando…':'Agregar usuario'}</Button></form>;
}

export function SupplierCategories(){
 const {settings,saveSettings,suppliers}=useEconexoData();const categories=settings?.supplier_categories??defaultSupplierCategories;
 const [name,setName]=useState(''),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const save=async()=>{if(name.trim().length<2){setMessage('Escribe al menos 2 caracteres.');return}if(categories.some(c=>c.id!==editing&&c.name.trim().toLocaleLowerCase()===name.trim().toLocaleLowerCase())){setMessage('Esta categoría ya existe.');return}setBusy(true);try{await saveSettings({supplier_categories:editing?categories.map(c=>c.id===editing?{...c,name:name.trim()}:c):[...categories,{id:crypto.randomUUID(),name:name.trim(),active:true}]});setName('');setEditing(null);setMessage('Categoría guardada.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}};
 return <><div className="settings-head"><h2>Categorías de abastecimiento</h2><p>Administra los grupos de proveedores que aparecen en Cadena de abastecimiento.</p></div><form onSubmit={e=>{e.preventDefault();void save()}}><div className="form-grid"><label>Nombre de la categoría<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Natural"/></label></div><div className="modal-actions"><Button disabled={busy} type="submit">{busy?'Guardando…':editing?'Guardar cambios':'Agregar categoría'}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing(null);setName('')}}>Cancelar</Button>}</div></form><p role="status">{message}</p><div className="history-list">{categories.map(c=><div key={c.id}><p><strong>{c.name}</strong><small>{suppliers.filter(p=>supplierCategoryId(p)===c.id).length} proveedores · {c.active?'Activa':'Inactiva'}</small></p><Button disabled={busy} variant="outline" onClick={()=>{setEditing(c.id);setName(c.name)}}>Editar</Button><Button disabled={busy} variant="ghost" onClick={async()=>{setBusy(true);try{await saveSettings({supplier_categories:categories.map(x=>x.id===c.id?{...x,active:!x.active}:x)})}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}}}>{c.active?'Desactivar':'Activar'}</Button></div>)}</div></>;
}
