'use client';
import {useState} from 'react';
import {Button} from './ui/button';
import {useEconexoData} from '@/lib/econexo-data';
import {defaultMaterialGroups} from '@/lib/material-groups';
import {defaultSupplierCategories} from '@/lib/supplier-categories';
import {codeDefaults,getCodeRule,nextCode,materialDisplayId,type CodeEntity} from '@/lib/code-rules';
import {supplierDisplayId,clientDisplayId} from '@/lib/party-codes';
export function CodeSettings(){
 const {settings,materials,clients,suppliers,saveSettings}=useEconexoData();
 const rules=settings?.code_rules??[],[entity,setEntity]=useState<CodeEntity>('material'),[category,setCategory]=useState('*');
 const initial=getCodeRule(rules,'material','*'),[prefix,setPrefix]=useState(initial.prefix),[digits,setDigits]=useState(initial.digits),[start,setStart]=useState(initial.start);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const groups=entity==='supplier'?(settings?.supplier_categories??defaultSupplierCategories):(settings?.material_groups??defaultMaterialGroups);
 const change=(e:CodeEntity,c:string)=>{const r=getCodeRule(rules,e,c);setEntity(e);setCategory(c);setPrefix(r.prefix);setDigits(r.digits);setStart(r.start);setError('');setMessage('')};
 const existing=entity==='material'?materials.map(materialDisplayId):entity==='client'?clients.map(clientDisplayId):suppliers.map(supplierDisplayId);
 let preview='Nomenclatura inválida';try{preview=nextCode({entity,category,prefix,digits,start},existing,settings?.code_counters?.[entity+':'+prefix]??0).code}catch{}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');const rule={entity,category,prefix,digits,start};
  try{nextCode(rule,existing,settings?.code_counters?.[entity+':'+prefix]??0);setBusy(true);await saveSettings({code_rules:[...rules.filter(r=>r.entity!==entity||r.category!==category),rule]});setMessage('Nomenclatura guardada. Se aplicará a los registros nuevos.')}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}
 };
 return <div className="codes-rules"><div className="settings-head"><h2>Códigos automáticos</h2><p>Define un prefijo y consecutivo general o uno por categoría. Los códigos existentes no cambian.</p></div><form onSubmit={save}><div className="form-grid"><label>Tipo de código<select value={entity} onChange={e=>change(e.target.value as CodeEntity,'*')}><option value="material">Código de materiales</option><option value="client">Código cliente</option><option value="supplier">Código proveedores</option></select></label><label>Categoría para nomenclatura<select value={category} onChange={e=>change(entity,e.target.value)}><option value="*">General / categorías sin regla propia</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Prefijo<input required minLength={2} maxLength={12} pattern="[A-Z0-9][A-Z0-9-]{1,11}" value={prefix} onChange={e=>setPrefix(e.target.value.toUpperCase().replace(/\s/g,''))} placeholder={codeDefaults[entity]}/></label><label>Dígitos del consecutivo<input required type="number" min="2" max="8" value={digits} onChange={e=>setDigits(Number(e.target.value))}/></label><label>Consecutivo inicial<input required type="number" min="1" max={10**digits-1} value={start} onChange={e=>setStart(Number(e.target.value))}/></label></div><div className="codes-preview">Próximo código estimado<strong>{preview}</strong></div><p className="chart-note">Materiales usan su categoría principal; proveedores usan su categoría de proveedor. Para clientes, selecciona la categoría del código en su formulario. El consecutivo no se reinicia al editar una regla.</p>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<div className="modal-actions"><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar nomenclatura'}</Button></div></form><h3>Nomenclaturas configuradas</h3><div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Categoría</th><th>Formato</th></tr></thead><tbody>{rules.map(r=><tr key={r.entity+':'+r.category}><td>{{material:'Material',client:'Cliente',supplier:'Proveedor'}[r.entity]}</td><td>{r.category==='*'?'General':(r.entity==='supplier'?(settings?.supplier_categories??defaultSupplierCategories):(settings?.material_groups??defaultMaterialGroups)).find(g=>g.id===r.category)?.name??r.category}</td><td>{r.prefix}-{'0'.repeat(r.digits)}</td></tr>)}{!rules.length&&<tr><td colSpan={3}>Se utilizan MAT, CLI y PROV con cuatro dígitos.</td></tr>}</tbody></table></div></div>;
}
