'use client';

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { announceTableChange } from '@/components/table-effects';
import { createClient } from '@/lib/supabase/client';

export type InventoryRecord = {id:string;inventory_code:string;received_at:string;material:string;category:string;material_id?:string;category_id?:string;supplier_id?:string;quantity:number;unit:'lb'|'ton';pounds:number;tons:number;supplier:string;supplier_type:'collector'|'company';delivered_by:string;status:'available'|'in_transit'|'reserved';notes?:string|null;currency?:'LPS'|'USD'|null;exchange_rate?:number|null;cost_price?:number|null;sale_price?:number|null;cost_total?:number|null;estimated_sale?:number|null;estimated_profit?:number|null};
export type SupplierRecord = {id:string;category_id?:string|null;supplier_code?:string;type:'collector'|'company';name:string;phone:string;identity_number?:string|null;rtn?:string|null;contact_name?:string|null;address?:string|null;notes?:string|null;active:boolean};
export type ClientRecord = {id:string;client_code?:string|null;type:'person'|'company';name:string;phone:string;address:string;tax_or_identity?:string|null;notes?:string|null;active:boolean;created_at?:string;material_ids?:string[];category_ids?:string[]};
export type MaterialRecord = {id:string;name:string;description?:string|null;active:boolean};
export type CategoryRecord = {id:string;material_id:string;name:string;active:boolean};
export type CompanySettings = {id:string;supplier_categories?:import('./supplier-categories').SupplierCategory[];name:string;logo_url?:string|null;default_currency:'LPS'|'USD';usd_to_lps_rate:number;default_weight_unit:'lb'|'ton';legal_name?:string|null;rtn?:string|null;fiscal_address?:string|null;fiscal_phone?:string|null;fiscal_email?:string|null;cai?:string|null;authorized_range_from?:number|null;authorized_range_to?:number|null;authorization_deadline?:string|null;establishment_code?:string|null;emission_point_code?:string|null;document_type_code?:string|null;next_invoice_correlative?:number|null};
export type ProfileRecord = {id:string;email?:string;full_name:string;avatar_url?:string|null;role:'admin'|'employee';active:boolean};
type InventoryInput={material_id:string;category_id:string;supplier_id:string;delivered_by:string;quantity:number;unit:'lb'|'ton';currency:'LPS'|'USD';cost_price:number;sale_price:number;exchange_rate:number;received_at:string;notes?:string;status?:'available'|'in_transit'|'reserved'};
type DataContextValue={createProfile:(input:{full_name:string;email:string;role:'admin'|'employee';password:string})=>Promise<void>;configured:boolean;demoMode:boolean;ready:boolean;loading:boolean;user:User|null;error:string;inventory:InventoryRecord[];suppliers:SupplierRecord[];clients:ClientRecord[];materials:MaterialRecord[];categories:CategoryRecord[];settings:CompanySettings|null;profiles:ProfileRecord[];signIn:(email:string,password:string)=>Promise<void>;signOut:()=>Promise<void>;refresh:()=>Promise<void>;createInventory:(input:InventoryInput)=>Promise<void>;updateInventory:(id:string,input:InventoryInput)=>Promise<void>;deleteInventory:(id:string)=>Promise<void>;saveSupplier:(input:Partial<SupplierRecord>&{name:string;phone:string;type:'collector'|'company'},id?:string)=>Promise<void>;supplierHistory:(id:string)=>Promise<Record<string,unknown>[]>;saveClient:(input:Partial<ClientRecord>&{name:string;phone:string;address:string;type:'person'|'company'},materialIds:string[],categoryIds:string[],id?:string)=>Promise<void>;clientHistory:(id:string)=>Promise<Record<string,unknown>[]>;saveSettings:(input:Partial<CompanySettings>)=>Promise<void>;saveMaterial:(name:string,id?:string)=>Promise<void>;saveCategory:(materialId:string,name:string,id?:string)=>Promise<void>;toggleMaterial:(id:string,active:boolean)=>Promise<void>;toggleCategory:(id:string,active:boolean)=>Promise<void>;saveProfile:(id:string,input:Partial<Pick<ProfileRecord,'full_name'|'role'|'active'>>)=>Promise<void>};

const ids={iron:'mat-iron',cardboard:'mat-cardboard',heavy:'cat-heavy',light:'cat-light',scrap:'cat-scrap',clean:'cat-clean',mixed:'cat-mixed'};
const demoMaterials:MaterialRecord[]=[{id:ids.iron,name:'Hierro',active:true},{id:ids.cardboard,name:'Cartón',active:true}];
const demoCategories:CategoryRecord[]=[{id:ids.heavy,material_id:ids.iron,name:'Hierro pesado',active:true},{id:ids.light,material_id:ids.iron,name:'Hierro liviano',active:true},{id:ids.scrap,material_id:ids.iron,name:'Chatarra',active:true},{id:ids.clean,material_id:ids.cardboard,name:'Cartón limpio',active:true},{id:ids.mixed,material_id:ids.cardboard,name:'Cartón mixto',active:true}];
const demoSuppliers:SupplierRecord[]=[{id:'sup-pedro',type:'collector',name:'Pedro',phone:'+504 9876-2341',address:'Tegucigalpa',active:true},{id:'sup-mario',type:'collector',name:'Mario',phone:'+504 9745-2210',address:'Comayagüela',active:true},{id:'sup-jose',type:'collector',name:'José',phone:'+504 9982-6108',address:'Valle de Ángeles',active:true},{id:'sup-demo',type:'company',name:'Demolición Centroamericana',phone:'+504 2231-8400',rtn:'08019022450123',contact_name:'Laura Méndez',address:'Tegucigalpa',active:true},{id:'sup-norte',type:'company',name:'Edificios del Norte',phone:'+504 2550-1932',contact_name:'Carlos Pérez',address:'San Pedro Sula',active:true}];
const demoClients:ClientRecord[]=[{id:'cli-pedro',type:'person',name:'Pedro de La Paz',phone:'+504 9981-2240',address:'La Paz, Honduras',tax_or_identity:'1201199000123',active:true,material_ids:[ids.iron],category_ids:[ids.heavy,ids.light]},{id:'cli-maria',type:'person',name:'María',phone:'+504 9732-0084',address:'Tegucigalpa, Honduras',active:true,material_ids:[ids.cardboard],category_ids:[ids.clean,ids.mixed]},{id:'cli-guatemala',type:'company',name:'Cliente Guatemala',phone:'+502 2290-8120',address:'Ciudad de Guatemala',tax_or_identity:'08019012345678',active:true,material_ids:[ids.iron,ids.cardboard],category_ids:[ids.scrap,ids.clean]}];
const demoSettings:CompanySettings={id:'company-demo',name:'Gavrion EcoSystems',legal_name:'Gavrion EcoSystems, S. de R.L.',rtn:'08019000000000',fiscal_address:'Tegucigalpa, Francisco Morazán, Honduras',fiscal_phone:'+504 2234-5678',fiscal_email:'facturacion@gavrion.example',cai:'CAI-DEMO-PENDIENTE-DE-REEMPLAZAR',authorized_range_from:1,authorized_range_to:5000,authorization_deadline:'2027-12-31',establishment_code:'000',emission_point_code:'001',document_type_code:'01',next_invoice_correlative:1001,default_currency:'LPS',usd_to_lps_rate:24.75,default_weight_unit:'lb'};
const demoProfiles:ProfileRecord[]=[{id:'demo-admin',full_name:'Ana Morales',role:'admin',active:true},{id:'demo-employee',full_name:'Carlos Mejía',role:'employee',active:true}];
const demoUser={id:'demo-admin',email:'admin@econexo.local'} as User;
const demoSales=[{client_id:'cli-pedro',sale_id:'sale-1',sold_at:'2026-09-05',material:'Hierro',category:'Hierro pesado',quantity:12,unit:'ton',currency:'LPS',total:100800},{client_id:'cli-maria',sale_id:'sale-2',sold_at:'2026-09-04',material:'Cartón',category:'Cartón limpio',quantity:7,unit:'ton',currency:'LPS',total:45500},{client_id:'cli-guatemala',sale_id:'sale-3',sold_at:'2026-09-03',material:'Hierro',category:'Chatarra',quantity:10,unit:'ton',currency:'USD',total:7800}];
const makeInventory=(id:string,code:string,input:InventoryInput,status:InventoryRecord['status']='available',lookups={materials:demoMaterials,categories:demoCategories,suppliers:demoSuppliers}):InventoryRecord=>{const material=lookups.materials.find(x=>x.id===input.material_id)?.name??'Material';const category=lookups.categories.find(x=>x.id===input.category_id)?.name??'Categoría';const supplier=lookups.suppliers.find(x=>x.id===input.supplier_id);const pounds=input.unit==='lb'?input.quantity:input.quantity*2000;const tons=input.unit==='ton'?input.quantity:input.quantity/2000;return{id,inventory_code:code,received_at:input.received_at,material,category,material_id:input.material_id,category_id:input.category_id,supplier_id:input.supplier_id,quantity:input.quantity,unit:input.unit,pounds,tons,supplier:supplier?.name??'Proveedor',supplier_type:supplier?.type??'collector',delivered_by:input.delivered_by,status:input.status??status,notes:input.notes,currency:input.currency,exchange_rate:input.exchange_rate,cost_price:input.cost_price,sale_price:input.sale_price,cost_total:input.quantity*input.cost_price,estimated_sale:input.quantity*input.sale_price,estimated_profit:input.quantity*(input.sale_price-input.cost_price)}};
const demoInventory:InventoryRecord[]=[makeInventory('inv-1','INV-02048',{material_id:ids.iron,category_id:ids.heavy,supplier_id:'sup-pedro',delivered_by:'Pedro Martínez',quantity:4000,unit:'lb',currency:'LPS',cost_price:6.2,sale_price:8.4,exchange_rate:24.75,received_at:'2026-09-05'}),makeInventory('inv-2','INV-02047',{material_id:ids.cardboard,category_id:ids.clean,supplier_id:'sup-demo',delivered_by:'Laura Méndez',quantity:1.8,unit:'ton',currency:'LPS',cost_price:4200,sale_price:6500,exchange_rate:24.75,received_at:'2026-09-05'},'in_transit'),makeInventory('inv-3','INV-02046',{material_id:ids.iron,category_id:ids.scrap,supplier_id:'sup-norte',delivered_by:'Carlos Pérez',quantity:2500,unit:'lb',currency:'USD',cost_price:.27,sale_price:.39,exchange_rate:24.75,received_at:'2026-09-04'},'reserved'),makeInventory('inv-4','INV-02045',{material_id:ids.cardboard,category_id:ids.mixed,supplier_id:'sup-mario',delivered_by:'Mario',quantity:980,unit:'lb',currency:'LPS',cost_price:1.85,sale_price:2.8,exchange_rate:24.75,received_at:'2026-09-04'}),makeInventory('inv-5','INV-02044',{material_id:ids.iron,category_id:ids.light,supplier_id:'sup-jose',delivered_by:'José',quantity:3.2,unit:'ton',currency:'LPS',cost_price:11600,sale_price:15900,exchange_rate:24.75,received_at:'2026-09-03'})];

const DataContext=createContext<DataContextValue|null>(null);const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);const storageKey='econexo-demo-data-v1';const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;

export function EconexoDataProvider({children}:{children:React.ReactNode}){
  const supabase=useMemo(()=>configured?createClient():null,[]);const[user,setUser]=useState<User|null>(configured?null:demoUser);const[ready,setReady]=useState(!configured);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[demoLoaded,setDemoLoaded]=useState(false);
  const[inventory,setInventory]=useState<InventoryRecord[]>(configured?[]:demoInventory);const[suppliers,setSuppliers]=useState<SupplierRecord[]>(configured?[]:demoSuppliers);const[clients,setClients]=useState<ClientRecord[]>(configured?[]:demoClients);const[materials,setMaterials]=useState<MaterialRecord[]>(configured?[]:demoMaterials);const[categories,setCategories]=useState<CategoryRecord[]>(configured?[]:demoCategories);const[settings,setSettings]=useState<CompanySettings|null>(configured?null:demoSettings);const[profiles,setProfiles]=useState<ProfileRecord[]>(configured?[]:demoProfiles);
  useEffect(()=>{if(configured||typeof window==='undefined')return;try{const saved=window.localStorage.getItem(storageKey);if(saved){const data=JSON.parse(saved);const savedSettings={...demoSettings,...(data.settings??{})};const legacyNames=['EcoNexo Reciclajes','EconoNexo Reciclajes','Gavrion Reciclajes'];setInventory(data.inventory??demoInventory);setSuppliers(data.suppliers??demoSuppliers);setClients(data.clients??demoClients);setMaterials(data.materials??demoMaterials);setCategories(data.categories??demoCategories);setSettings(legacyNames.includes(savedSettings.name)?{...savedSettings,name:'Gavrion EcoSystems'}:savedSettings);setProfiles(data.profiles??demoProfiles)}}catch{setError('No fue posible recuperar los datos locales.')}finally{setDemoLoaded(true)}},[]);
  useEffect(()=>{if(configured||!demoLoaded||typeof window==='undefined')return;window.localStorage.setItem(storageKey,JSON.stringify({inventory,suppliers,clients,materials,categories,settings,profiles}))},[demoLoaded,inventory,suppliers,clients,materials,categories,settings,profiles]);
  const refresh=useCallback(async()=>{if(!supabase||!user)return;setLoading(true);setError('');const[inv,sup,cli,mat,cat,cfg,pro,cm,cc]=await Promise.all([supabase.from('v_inventory_detail').select('*').order('received_at',{ascending:false}),supabase.from('suppliers').select('*').order('name'),supabase.from('clients').select('*').order('name'),supabase.from('materials').select('*').order('name'),supabase.from('categories').select('*').order('name'),supabase.from('company_settings').select('*').limit(1).maybeSingle(),supabase.from('profiles').select('*').order('full_name'),supabase.from('client_materials').select('client_id,material_id'),supabase.from('client_categories').select('client_id,category_id')]);const first=[inv,sup,cli,mat,cat,cfg,pro,cm,cc].find(x=>x.error)?.error;if(first)setError(first.message);else{setInventory((inv.data??[])as InventoryRecord[]);setSuppliers((sup.data??[])as SupplierRecord[]);setClients(((cli.data??[])as ClientRecord[]).map(row=>({...row,material_ids:(cm.data??[]).filter(x=>x.client_id===row.id).map(x=>x.material_id),category_ids:(cc.data??[]).filter(x=>x.client_id===row.id).map(x=>x.category_id)})));setMaterials((mat.data??[])as MaterialRecord[]);setCategories((cat.data??[])as CategoryRecord[]);setSettings(cfg.data as CompanySettings|null);setProfiles((pro.data??[])as ProfileRecord[])}setLoading(false)},[supabase,user]);
  useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setReady(true)});return()=>data.subscription.unsubscribe()},[supabase]);useEffect(()=>{if(user&&supabase)void refresh()},[user,supabase,refresh]);
  const run=async(action:()=>Promise<{error:{message:string}|null}>)=>{setLoading(true);setError('');const{error:e}=await action();if(e){setLoading(false);setError(e.message);throw new Error(e.message)}await refresh();setLoading(false)};
  const signIn=async(email:string,password:string)=>{if(!supabase){setUser(demoUser);return}setLoading(true);const{error:e}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(e)throw e};const signOut=async()=>{if(supabase){await supabase.auth.signOut();setUser(null)}};
  const createInventory=async(input:InventoryInput)=>{if(!supabase){const newId=uid('inv');announceTableChange(newId,'created');setInventory(cur=>[makeInventory(newId,`INV-${String(2049+cur.length).padStart(5,'0')}`,input,'available',{materials,categories,suppliers}),...cur]);return}await run(async()=>{const{data,error}=await supabase.rpc('create_inventory_entry',{p_material_id:input.material_id,p_category_id:input.category_id,p_supplier_id:input.supplier_id,p_delivered_by:input.delivered_by,p_quantity:input.quantity,p_unit:input.unit,p_currency:input.currency,p_cost_price:input.cost_price,p_sale_price:input.sale_price,p_exchange_rate:input.exchange_rate,p_received_at:input.received_at,p_notes:input.notes||null});if(error||!data)return{error};const result=await supabase.from('inventory_entries').update({status:input.status??'available'}).eq('id',data);if(!result.error)announceTableChange(data,'created');return{error:result.error}})};
  const updateInventory=async(id:string,input:InventoryInput)=>{if(!supabase){announceTableChange(id,'updated');setInventory(cur=>cur.map(old=>old.id===id?makeInventory(id,old.inventory_code,input,old.status,{materials,categories,suppliers}):old));return}await run(async()=>{const{error}=await supabase.rpc('update_inventory_entry',{p_entry_id:id,p_material_id:input.material_id,p_category_id:input.category_id,p_supplier_id:input.supplier_id,p_delivered_by:input.delivered_by,p_quantity:input.quantity,p_unit:input.unit,p_currency:input.currency,p_cost_price:input.cost_price,p_sale_price:input.sale_price,p_exchange_rate:input.exchange_rate,p_received_at:input.received_at,p_notes:input.notes||null});if(error)return{error};const result=await supabase.from('inventory_entries').update({status:input.status??'available'}).eq('id',id);if(!result.error)announceTableChange(id,'updated');return{error:result.error}})};
  const deleteInventory=async(id:string)=>{if(!supabase){setInventory(cur=>cur.filter(x=>x.id!==id));return}await run(async()=>{const{error}=await supabase.from('inventory_entries').delete().eq('id',id);return{error}})};
  const saveSupplier=async(input:Partial<SupplierRecord>&{name:string;phone:string;type:'collector'|'company'},id?:string)=>{if(!supabase){setSuppliers(cur=>id?cur.map(x=>x.id===id?{...x,...input}:x):[...cur,{id:uid('sup'),active:true,...input}]);return}await run(async()=>{const q=id?supabase.from('suppliers').update(input).eq('id',id):supabase.from('suppliers').insert(input);const{error}=await q;return{error}})};
  const supplierHistory=async(id:string)=>{if(!supabase)return inventory.filter(x=>x.supplier_id===id).map(x=>({supplier_id:id,inventory_entry_id:x.id,received_at:x.received_at,material:x.material,category:x.category,quantity:x.quantity,unit:x.unit,currency:x.currency,cost_total:x.cost_total}));const{data,error}=await supabase.from('v_supplier_history').select('*').eq('supplier_id',id).order('received_at',{ascending:false});if(error)throw error;return data??[]};
  const saveClient=async(input:Partial<ClientRecord>&{name:string;phone:string;address:string;type:'person'|'company'},materialIds:string[],categoryIds:string[],id?:string)=>{if(!supabase){setClients(cur=>id?cur.map(x=>x.id===id?{...x,...input,material_ids:materialIds,category_ids:categoryIds}:x):[...cur,{id:uid('cli'),active:true,...input,material_ids:materialIds,category_ids:categoryIds}]);return}setLoading(true);let clientId=id;if(id){const{error}=await supabase.from('clients').update(input).eq('id',id);if(error)throw error}else{const{data,error}=await supabase.from('clients').insert(input).select('id').single();if(error)throw error;clientId=data.id}await Promise.all([supabase.from('client_materials').delete().eq('client_id',clientId!),supabase.from('client_categories').delete().eq('client_id',clientId!)]);if(materialIds.length)await supabase.from('client_materials').insert(materialIds.map(material_id=>({client_id:clientId,material_id})));if(categoryIds.length)await supabase.from('client_categories').insert(categoryIds.map(category_id=>({client_id:clientId,category_id})));await refresh();setLoading(false)};
  const clientHistory=async(id:string)=>{if(!supabase)return demoSales.filter(x=>x.client_id===id);const{data,error}=await supabase.from('v_client_history').select('*').eq('client_id',id).order('sold_at',{ascending:false});if(error)throw error;return data??[]};
  const saveSettings=async(input:Partial<CompanySettings>)=>{if(!supabase){setSettings(cur=>({...demoSettings,...cur,...input}));return}await run(async()=>{const q=settings?supabase.from('company_settings').update(input).eq('id',settings.id):supabase.from('company_settings').insert(input);const{error}=await q;return{error}})};
  const saveMaterial=async(name:string,id?:string)=>{if(!supabase){setMaterials(cur=>id?cur.map(x=>x.id===id?{...x,name}:x):[...cur,{id:uid('mat'),name,active:true}]);return}await run(async()=>{const q=id?supabase.from('materials').update({name}).eq('id',id):supabase.from('materials').insert({name});const{error}=await q;return{error}})};
  const saveCategory=async(materialId:string,name:string,id?:string)=>{if(!supabase){setCategories(cur=>id?cur.map(x=>x.id===id?{...x,material_id:materialId,name}:x):[...cur,{id:uid('cat'),material_id:materialId,name,active:true}]);return}await run(async()=>{const q=id?supabase.from('categories').update({material_id:materialId,name}).eq('id',id):supabase.from('categories').insert({material_id:materialId,name});const{error}=await q;return{error}})};
  const toggleMaterial=async(id:string,active:boolean)=>{if(!supabase){setMaterials(cur=>cur.map(x=>x.id===id?{...x,active}:x));return}await run(async()=>{const{error}=await supabase.from('materials').update({active}).eq('id',id);return{error}})};const toggleCategory=async(id:string,active:boolean)=>{if(!supabase){setCategories(cur=>cur.map(x=>x.id===id?{...x,active}:x));return}await run(async()=>{const{error}=await supabase.from('categories').update({active}).eq('id',id);return{error}})};const saveProfile=async(id:string,input:Partial<Pick<ProfileRecord,'full_name'|'role'|'active'>>)=>{if(!supabase){setProfiles(cur=>cur.map(x=>x.id===id?{...x,...input}:x));return}await run(async()=>{const{error}=await supabase.from('profiles').update(input).eq('id',id);return{error}})};
  const createProfile=async(input:{full_name:string;email:string;role:'admin'|'employee';password:string})=>{
    if(!profiles.some(p=>p.id===user?.id&&p.role==='admin'&&p.active))throw new Error('Acceso de administrador requerido');
    if(!supabase){if(profiles.some(p=>p.email?.toLowerCase()===input.email.toLowerCase()))throw new Error('El correo ya está registrado');setProfiles(cur=>[...cur,{id:uid('user'),full_name:input.full_name,email:input.email,role:input.role,active:true}]);return;}
    const {data}=await supabase.auth.getSession();
    const response=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session?.access_token},body:JSON.stringify(input)});
    const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo crear el usuario');await refresh();
  };
  return <DataContext.Provider value={{createProfile,configured,demoMode:!configured,ready,loading,user,error,inventory,suppliers,clients,materials,categories,settings,profiles,signIn,signOut,refresh,createInventory,updateInventory,deleteInventory,saveSupplier,supplierHistory,saveClient,clientHistory,saveSettings,saveMaterial,saveCategory,toggleMaterial,toggleCategory,saveProfile}}>{children}</DataContext.Provider>;
}
export function useEconexoData(){const value=useContext(DataContext);if(!value)throw new Error('useEconexoData requiere EconexoDataProvider');return value}
